apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customerapp
  template:
    metadata:
      labels:
        app: customerapp
    spec:
      containers:
        - name: customerapp
          image: 390278047930.dkr.ecr.us-east-1.amazonaws.com/customerapp-repo:latest
          ports:
            - containerPort: 8080